package fasthttp

import "path"

func GetContentType(file string) string {
	ContentType := make(map[string]string)

	ContentType[".aac"] = "audio/aac"
	ContentType[".abw"] = "application/x-abiword"
	ContentType[".arc"] = "application/octet-stream"
	ContentType[".avi"] = "video/x-msvideo"
	ContentType[".azw"] = "application/vnd.amazon.ebook"
	ContentType[".bin"] = "application/octet-stream"
	ContentType[".bz"] = "application/x-bzip"
	ContentType[".bz2"] = "application/x-bzip2"
	ContentType[".csh"] = "application/x-csh"
	ContentType[".css"] = "text/css"
	ContentType[".csv"] = "text/csv"
	ContentType[".doc"] = "application/msword"
	ContentType[".epub"] = "application/epub+zip"
	ContentType[".gif"] = "image/gif"
	ContentType[".htm"] = "text/html"
	ContentType[".html"] = "text/html"
	ContentType[".ico"] = "image/x-icon"
	ContentType[".ics"] = "text/calendar"
	ContentType[".jar"] = "application/java-archive"
	ContentType[".jpeg"] = "image/jpeg"
	ContentType[".jpg"] = "image/jpeg"
	ContentType[".js"] = "application/javascript"
	ContentType[".json"] = "application/json"
	ContentType[".mid"] = "audio/midi"
	ContentType[".midi"] = "audio/midi"
	ContentType[".mpeg"] = "vieo/mpeg"
	ContentType[".mpkg"] = "application/vnd.apple.installer+xml"
	ContentType[".odp"] = "application/vnd.oasis.opendocument.presentation"
	ContentType[".ods"] = "application/vnd.oasis.opendocument.spreadsheet"
	ContentType[".odt"] = "application/vnd.oasis.opendocument.text"
	ContentType[".oga"] = "audio/ogg"
	ContentType[".ogv"] = "audio/ogg"
	ContentType[".ogx"] = "application/ogg"
	ContentType[".pdf"] = "application/pdf"
	ContentType[".ppt"] = "application/vnd.ms-powerpoint"
	ContentType[".rar"] = "application/x-rar-compressed"
	ContentType[".rft"] = "application/rtf"
	ContentType[".sh"] = "application/x-sh"
	ContentType[".svg"] = "image/svg+xml"
	ContentType[".swf"] = "application/x-shockwave-flash"
	ContentType[".tar"] = "application/x-tar"
	ContentType[".tif"] = "image/tiff"
	ContentType[".tiff"] = "image/ttif"
	ContentType[".ttf"] = "font/ttf"
	ContentType[".vsd"] = "application/vnd.visio"
	ContentType[".weba"] = "audio/webm"
	ContentType[".webm"] = "video/webm"
	ContentType[".wav"] = "audio/x-wav"
	ContentType[".webp"] = "image/webp"
	ContentType[".woff"] = "font/woff"
	ContentType[".woff2"] = "font/woff2"
	ContentType[".xhtml"] = "application/xhtml+xml"
	ContentType[".xls"] = "application/vnd.ms-excel"
	ContentType[".xml"] = "application/xml"
	ContentType[".xul"] = "application/vnd.mozilla.xul+xml"
	ContentType[".zip"] = "application/zip"
	ContentType[".3gp"] = "video/3gpp"
	ContentType[".3g2"] = "video/3gpp2"
	ContentType[".7z"] = "application/x-7z-compressed"

	return ContentType[path.Ext(file)]
}
